// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfscluvokrotqrnachae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmc2NsdXZva3JvdHFybmFjaGFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNjIxMzUsImV4cCI6MjA2NzczODEzNX0.iEPwGy5NpmuWsWX0MUVApK27f_7o50Vm5Ttyg-uE4rM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});